# Generated by Django 2.2.5 on 2019-12-06 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Reservar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adultos', models.IntegerField(verbose_name='Quantos Adultos')),
                ('quantidade', models.IntegerField(verbose_name='Informe a quantidade de Apartamentos Solicitados')),
                ('criancas', models.IntegerField(verbose_name='Quantas Crianças')),
                ('cpf', models.IntegerField(verbose_name='Informar o CPF')),
                ('cafe', models.BooleanField(blank=True, null=True, verbose_name='Apartamento com Café da Manhã?')),
                ('celular', models.IntegerField(verbose_name='Informe o Número do seu celular')),
                ('entrada', models.DateField(verbose_name='Informe a sua Data de Entrada')),
                ('saida', models.DateField(verbose_name='Informe a sua Data de Saída')),
                ('apartamentos', models.ManyToManyField(to='core.Apartamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
