# Generated by Django 2.2.5 on 2019-12-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservar',
            name='cafe',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Apartamento com Café da Manhã?'),
        ),
    ]
